name: Run Python Script

on:
  schedule:
    - cron: '30 15 * * *' # Runs at 3:10 PM UTC
  workflow_dispatch:  # Enable manual triggering

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.x'

      - name: Check out repository
        uses: actions/checkout@v4.1.2

      - name: Run Python Script
        run: test_script_schedule.py
