name: Run Python Script

on: 
  schedule:
    - cron: '10 20 * * *'

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: action/setup-python@v5.1.0
        with:
          python-version: '3.x'

      - name: Check out repository
        uses: actions/checkout@v4.1.2

      - name: Run Python Script
        run: test_script_schedule.py
        
